//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabardo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN
    {
        public int Id { get; set; }
        public double LoanAmount { get; set; }
        public double Interest { get; set; }
        public string Term { get; set; }
        public int Number { get; set; }
        public Nullable<double> Deduction { get; set; }
        public double InterestedAmount { get; set; }
        public double ReceivedAmount { get; set; }
        public double TotalPayable { get; set; }
        public System.DateTime DueDate { get; set; }
        public string Status { get; set; }
    }
}
