//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabardo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAN
    {
        public int Id { get; set; }
        public Nullable<double> LoanAmount { get; set; }
        public Nullable<double> Interest { get; set; }
        public string Term { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<double> Deduction { get; set; }
        public Nullable<double> InterestedAmount { get; set; }
        public Nullable<double> ReceivedAmount { get; set; }
        public Nullable<double> TotalPayable { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
