//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabardo.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ambotEntities2 : DbContext
    {
        public ambotEntities2()
            : base("name=ambotEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<LOAN> LOANs { get; set; }
        public virtual DbSet<PAYMENTSCHEDULE> PAYMENTSCHEDULEs { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    }
}
